### ISSUE TITLE
是不是只能以团支书身份登录

### ISSUE THREAD

**Issue by XZ1314XZ** [CocaineCong/TeenStudy#1]
可以自己设置一键提醒吗

**Comment by CocaineCong** [comment]
是的，只适合福建的团支书身份登陆

**Comment by zhang1597664** [comment]
能改地方吗

**Comment by CocaineCong** [comment]
目前只有两个脚本，一个适合福建，一个适合安徽，如果需要其他地方的可以去我博客私聊我~

**Comment by yehuzhucha** [comment]
> 目前只有两个脚本，一个适合福建，一个适合安徽，如果需要其他地方的可以去我博客私聊我~

大佬晚上好，请问可以出一个利用action每周自动完成青年大学习的教程吗，直接完成学习，不更省事儿嘛大佬，我在github上看到了有几个成品但没有教程以及省份似乎也不同，不知大佬是否有这方面意愿
